# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.5
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_slurm.models.v0043_openapi_assocs_resp import V0043OpenapiAssocsResp

class TestV0043OpenapiAssocsResp(unittest.TestCase):
    """V0043OpenapiAssocsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043OpenapiAssocsResp:
        """Test V0043OpenapiAssocsResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043OpenapiAssocsResp`
        """
        model = V0043OpenapiAssocsResp()
        if include_optional:
            return V0043OpenapiAssocsResp(
                associations = [
                    openapi_slurm.models.v0/0/43_assoc.v0.0.43_assoc(
                        accounting = [
                            openapi_slurm.models.v0/0/43_accounting.v0.0.43_accounting(
                                allocated = openapi_slurm.models.v0_0_42_accounting_allocated.v0_0_42_accounting_allocated(
                                    seconds = 56, ),
                                id = 56,
                                id_alt = 56,
                                start = 56,
                                tres = openapi_slurm.models.v0/0/43_tres.v0.0.43_tres(
                                    type = '',
                                    name = '',
                                    id = 56,
                                    count = 56, ), )
                            ],
                        account = '',
                        cluster = '',
                        comment = '',
                        default = openapi_slurm.models.v0_0_40_assoc_default.v0_0_40_assoc_default(
                            qos = '', ),
                        flags = [
                            'DELETED'
                            ],
                        max = openapi_slurm.models.v0_0_43_assoc_max.v0_0_43_assoc_max(
                            jobs = openapi_slurm.models.v0_0_43_assoc_max_jobs.v0_0_43_assoc_max_jobs(
                                per = openapi_slurm.models.v0_0_43_assoc_max_jobs_per.v0_0_43_assoc_max_jobs_per(
                                    count = openapi_slurm.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                                        set = True,
                                        infinite = True,
                                        number = 56, ),
                                    accruing = openapi_slurm.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                                        set = True,
                                        infinite = True,
                                        number = 56, ),
                                    submitted = ,
                                    wall_clock = , ),
                                active = ,
                                accruing = ,
                                total = , ),
                            tres = openapi_slurm.models.v0_0_43_assoc_max_tres.v0_0_43_assoc_max_tres(
                                group = openapi_slurm.models.v0_0_43_assoc_max_tres_group.v0_0_43_assoc_max_tres_group(
                                    minutes = [
                                        openapi_slurm.models.v0/0/43_tres.v0.0.43_tres(
                                            type = '',
                                            name = '',
                                            id = 56, )
                                        ], ),
                                minutes = openapi_slurm.models.v0_0_43_assoc_max_tres_minutes.v0_0_43_assoc_max_tres_minutes(), ),
                            per = openapi_slurm.models.v0_0_43_assoc_max_per.v0_0_43_assoc_max_per(
                                account = openapi_slurm.models.v0_0_43_assoc_max_per_account.v0_0_43_assoc_max_per_account(), ), ),
                        id = 56,
                        is_default = True,
                        lineage = '',
                        min = openapi_slurm.models.v0_0_43_assoc_min.v0_0_43_assoc_min(
                            priority_threshold = , ),
                        parent_account = '',
                        partition = '',
                        priority = ,
                        qos = [
                            ''
                            ],
                        shares_raw = 56,
                        user = '', )
                    ],
                meta = openapi_slurm.models.v0/0/43_openapi_meta.v0.0.43_openapi_meta(
                    plugin = openapi_slurm.models.v0_0_40_openapi_meta_plugin.v0_0_40_openapi_meta_plugin(
                        type = '',
                        name = '',
                        data_parser = '',
                        accounting_storage = '', ),
                    client = openapi_slurm.models.v0_0_40_openapi_meta_client.v0_0_40_openapi_meta_client(
                        source = '',
                        user = '',
                        group = '', ),
                    command = [
                        ''
                        ],
                    slurm = openapi_slurm.models.v0_0_40_openapi_meta_slurm.v0_0_40_openapi_meta_slurm(
                        version = openapi_slurm.models.v0_0_40_openapi_meta_slurm_version.v0_0_40_openapi_meta_slurm_version(
                            major = '',
                            micro = '',
                            minor = '', ),
                        release = '',
                        cluster = '', ), ),
                errors = [
                    openapi_slurm.models.v0/0/43_openapi_error.v0.0.43_openapi_error(
                        description = '',
                        error_number = 56,
                        error = '',
                        source = '', )
                    ],
                warnings = [
                    openapi_slurm.models.v0/0/43_openapi_warning.v0.0.43_openapi_warning(
                        description = '',
                        source = '', )
                    ]
            )
        else:
            return V0043OpenapiAssocsResp(
                associations = [
                    openapi_slurm.models.v0/0/43_assoc.v0.0.43_assoc(
                        accounting = [
                            openapi_slurm.models.v0/0/43_accounting.v0.0.43_accounting(
                                allocated = openapi_slurm.models.v0_0_42_accounting_allocated.v0_0_42_accounting_allocated(
                                    seconds = 56, ),
                                id = 56,
                                id_alt = 56,
                                start = 56,
                                tres = openapi_slurm.models.v0/0/43_tres.v0.0.43_tres(
                                    type = '',
                                    name = '',
                                    id = 56,
                                    count = 56, ), )
                            ],
                        account = '',
                        cluster = '',
                        comment = '',
                        default = openapi_slurm.models.v0_0_40_assoc_default.v0_0_40_assoc_default(
                            qos = '', ),
                        flags = [
                            'DELETED'
                            ],
                        max = openapi_slurm.models.v0_0_43_assoc_max.v0_0_43_assoc_max(
                            jobs = openapi_slurm.models.v0_0_43_assoc_max_jobs.v0_0_43_assoc_max_jobs(
                                per = openapi_slurm.models.v0_0_43_assoc_max_jobs_per.v0_0_43_assoc_max_jobs_per(
                                    count = openapi_slurm.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                                        set = True,
                                        infinite = True,
                                        number = 56, ),
                                    accruing = openapi_slurm.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                                        set = True,
                                        infinite = True,
                                        number = 56, ),
                                    submitted = ,
                                    wall_clock = , ),
                                active = ,
                                accruing = ,
                                total = , ),
                            tres = openapi_slurm.models.v0_0_43_assoc_max_tres.v0_0_43_assoc_max_tres(
                                group = openapi_slurm.models.v0_0_43_assoc_max_tres_group.v0_0_43_assoc_max_tres_group(
                                    minutes = [
                                        openapi_slurm.models.v0/0/43_tres.v0.0.43_tres(
                                            type = '',
                                            name = '',
                                            id = 56, )
                                        ], ),
                                minutes = openapi_slurm.models.v0_0_43_assoc_max_tres_minutes.v0_0_43_assoc_max_tres_minutes(), ),
                            per = openapi_slurm.models.v0_0_43_assoc_max_per.v0_0_43_assoc_max_per(
                                account = openapi_slurm.models.v0_0_43_assoc_max_per_account.v0_0_43_assoc_max_per_account(), ), ),
                        id = 56,
                        is_default = True,
                        lineage = '',
                        min = openapi_slurm.models.v0_0_43_assoc_min.v0_0_43_assoc_min(
                            priority_threshold = , ),
                        parent_account = '',
                        partition = '',
                        priority = ,
                        qos = [
                            ''
                            ],
                        shares_raw = 56,
                        user = '', )
                    ],
        )
        """

    def testV0043OpenapiAssocsResp(self):
        """Test V0043OpenapiAssocsResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
